V_W1 <- read.table("V_W1.txt")
xrange <- range(0,500)
yrange <- range(0.3,1)
plot(xrange,yrange,type="n",ann=FALSE)
lines(V_W1, type="l", col="red")
V_W1b <-read.table("../2/V_W1.txt")
lines(V_W1b, type="l", col="blue")
V_W1c <-read.table("../3/V_W1.txt")
lines(V_W1c, type="l", col="black")
V_W1d <-read.table("../4/V_W1.txt")
lines(V_W1d, type="l", col="green")
V_W1e <-read.table("../5/V_W1.txt")
lines(V_W1e, type="l", col="purple")
title(main="Taxa = 0,2", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="Var(W1)", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
