n1 <- read.table("N1.txt")
xrange <- range(0,500)
yrange <- range(0.63,1)
plot(xrange,yrange,type="n",ann=FALSE)
lines(n1, type="l", col="red")
n1b <-read.table("../2/N1.txt")
lines(n1b, type="l", col="blue")
n1c <-read.table("../3/N1.txt")
lines(n1c, type="l", col="black")
n1d <-read.table("../4/N1.txt")
lines(n1d, type="l", col="green")
n1e <-read.table("../5/N1.txt")
lines(n1e, type="l", col="purple")
title(main="Taxa = 0,45", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[N1]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
