Nq1 <- read.table("Nq1.txt")
xrange <- range(0,500)
yrange <- range(0.25,0.5)
plot(xrange,yrange,type="n",ann=FALSE)
lines(Nq1, type="l", col="red")
Nq1b <-read.table("../2/Nq1.txt")
lines(Nq1b, type="l", col="blue")
Nq1c <-read.table("../3/Nq1.txt")
lines(Nq1c, type="l", col="black")
Nq1d <-read.table("../4/Nq1.txt")
lines(Nq1d, type="l", col="green")
Nq1e <-read.table("../5/Nq1.txt")
lines(Nq1e, type="l", col="purple")
title(main="Taxa = 0,45", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[Nq1]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
