N2 <- read.table("N2.txt")
xrange <- range(0,500)
yrange <- range(3.5,20)
plot(xrange,yrange,type="n",ann=FALSE)
lines(N2, type="l", col="red")
N2b <-read.table("../2/N2.txt")
lines(N2b, type="l", col="blue")
N2c <-read.table("../3/N2.txt")
lines(N2c, type="l", col="black")
N2d <-read.table("../4/N2.txt")
lines(N2d, type="l", col="green")
N2e <-read.table("../5/N2.txt")
lines(N2e, type="l", col="purple")
title(main="Taxa = 0,45", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[N2]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
