W1 <- read.table("W1.txt")
xrange <- range(0,500)
yrange <- range(0.7,1)
plot(xrange,yrange,type="n",ann=FALSE)
lines(W1, type="l", col="red")
W1b <-read.table("../2/W1.txt")
lines(W1b, type="l", col="blue")
W1c <-read.table("../3/W1.txt")
lines(W1c, type="l", col="black")
W1d <-read.table("../4/W1.txt")
lines(W1d, type="l", col="green")
W1e <-read.table("../5/W1.txt")
lines(W1e, type="l", col="purple")
title(main="Taxa = 0,45", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[W1]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
