W2 <- read.table("W2.txt")
xrange <- range(0,500)
yrange <- range(0.3,0.76)
plot(xrange,yrange,type="n",ann=FALSE)
lines(W2, type="l", col="red")
W2b <-read.table("../2/W2.txt")
lines(W2b, type="l", col="blue")
W2c <-read.table("../3/W2.txt")
lines(W2c, type="l", col="black")
W2d <-read.table("../4/W2.txt")
lines(W2d, type="l", col="green")
W2e <-read.table("../5/W2.txt")
lines(W2e, type="l", col="purple")
title(main="Taxa = 0,1", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[W2]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
