Nq2 <- read.table("Nq2.txt")
xrange <- range(0,500)
yrange <- range(0.23,0.4)
plot(xrange,yrange,type="n",ann=FALSE)
lines(Nq2, type="l", col="red")
Nq2b <-read.table("../2/Nq2.txt")
lines(Nq2b, type="l", col="blue")
Nq2c <-read.table("../3/Nq2.txt")
lines(Nq2c, type="l", col="black")
Nq2d <-read.table("../4/Nq2.txt")
lines(Nq2d, type="l", col="green")
Nq2e <-read.table("../5/Nq2.txt")
lines(Nq2e, type="l", col="purple")
title(main="Taxa = 0,2", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[Nq2]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
