T2 <- read.table("T2.txt")
xrange <- range(0,500)
yrange <- range(2.1,2.9)
plot(xrange,yrange,type="n",ann=FALSE)
lines(T2, type="l", col="red")
T2b <-read.table("../2/T2.txt")
lines(T2b, type="l", col="blue")
T2c <-read.table("../3/T2.txt")
lines(T2c, type="l", col="black")
T2d <-read.table("../4/T2.txt")
lines(T2d, type="l", col="green")
T2e <-read.table("../5/T2.txt")
lines(T2e, type="l", col="purple")
title(main="Taxa = 0,2", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[T2]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
