T1 <- read.table("T1.txt")
xrange <- range(0,500)
yrange <- range(1.18,1.4)
plot(xrange,yrange,type="n",ann=FALSE)
lines(T1, type="l", col="red")
T1b <-read.table("../2/T1.txt")
lines(T1b, type="l", col="blue")
T1c <-read.table("../3/T1.txt")
lines(T1c, type="l", col="black")
T1d <-read.table("../4/T1.txt")
lines(T1d, type="l", col="green")
T1e <-read.table("../5/T1.txt")
lines(T1e, type="l", col="purple")
title(main="Taxa = 0,2", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[T1]", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
