w1 <- read.table("W2.txt")
xrange <- range(0,400)
yrange <- range(1.0,2.2)
plot(xrange,yrange,type="n",ann=FALSE)
lines(w1, type="l", col="red")
w1b <-read.table("../2/W2.txt")
lines(w1b, type="l", col="blue")
w1c <-read.table("../3/W2.txt")
lines(w1c, type="l", col="black")
w1d <-read.table("../4/W2.txt")
lines(w1d, type="l", col="green")
w1e <-read.table("../5/W2.txt")
lines(w1e, type="l", col="purple")
title(main="Taxa = 0.2", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="E[W2]", col.main="black")
legend(50, 2.1, c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostra", lty=1)
