V_W2 <- read.table("V_W2.txt")
xrange <- range(0,500)
yrange <- range(3.6,9)
plot(xrange,yrange,type="n",ann=FALSE)
lines(V_W2, type="l", col="red")
V_W2b <-read.table("../2/V_W2.txt")
lines(V_W2b, type="l", col="blue")
V_W2c <-read.table("../3/V_W2.txt")
lines(V_W2c, type="l", col="black")
V_W2d <-read.table("../4/V_W2.txt")
lines(V_W2d, type="l", col="green")
V_W2e <-read.table("../5/V_W2.txt")
lines(V_W2e, type="l", col="purple")
title(main="Taxa = 0,2", col.main="black", font.main=4)
title(xlab="Rodadas", col.main="black")
title(ylab="Var(W2)", col.main="black")
legend(max(xrange)/5, max(yrange), c("1","2","3","4","5"), cex=0.8, col=c("red","blue","black","green","purple"),title="Amostras", lty=1)
